inherit_from: .rubocop_todo.yml

# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
Layout/IndentationWidth:
  Width: 5

Naming/MethodName:
  Enabled: true
  EnforcedStyle: snake_case 

Naming/ClassAndModuleCamelCase:
  Enabled: true